### ISSUE TITLE
__init__.py AttributeError

### ISSUE THREAD

**Issue by dotSlashLu** [agronholm/apscheduler#126] opened 2016-04-09 03:39 UTC
```
Traceback (most recent call last):
  File "ip_check.py", line 3, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public'
```
Installed from pip, version 3.1.0, Python 2.7.9, Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

**Comment by agronholm** [comment] 2016-04-09 10:13
Duplicate of #123, already fixed in f559affa716345157044243ac042625bcfcb9079.

**Closed by agronholm** 2016-04-09 10:13 UTC
Labels: duplicate
