### ISSUE TITLE
Sometimes APScheduler jobs are not executed as scheduled, Even when there is no error in logs.

### ISSUE THREAD

**Issue by dineshgawali** [agronholm/apscheduler#481] opened 2020-12-22 10:11 UTC
I am trying to run apscheduler with gunicorn and supervisord. Without gunicorn, apscheduler is working but sometimes with gunicorn, apscheduler does not work. Except apscheduler, other project is working. I am using following command to run using gunicorn. there are no errors in scheduler logs. 

## Expected Behavior
Every jobs must be executed as scheduled.

## Current Behavior
some scheduled jobs are not getting executed.

## Steps to Reproduce

1. setting the job in views.py file  
2. settings.scheduler.add_job(function_to_run, 'date', jobstore='redis', replace_existing=True,
    run_date=start_datetime_of_job, misfire_grace_time=None,
    id="start-" + str(model_object.id),args=[args list])
3. job was missed, the function "looking for job to next run" not execute.

## Context (Environment)
In settings.py file

```from apscheduler.schedulers.background import BackgroundScheduler

from apscheduler.jobstores.redis import RedisJobStore
from apscheduler.executors.pool import ThreadPoolExecutor, ProcessPoolExecutor

logging.basicConfig(filename='logs/scheduler', level=logging.DEBUG,format='[%(asctime)s]: %(levelname)s : %(message)s')
logging.getLogger('apscheduler').setLevel(logging.DEBUG)


scheduler = BackgroundScheduler({'apscheduler.timezone': 'Asia/Calcutta'},job_defaults={'misfire_grace_time': None})
scheduler.add_jobstore(RedisJobStore(jobs_key='dev-jobs', run_times_key='dev_all_run_times'), 'redis')
scheduler.start()
```

## Detailed Description
With normal runserver every job is executed on time but using gunicorn some job is not executing 
I am using following command in supervisord.conf file to run project
```
/home/ubuntu/project/project_folder/venv/bin/gunicorn project.wsgi:application  --timeout 120 --workers 2 --threads=3 --bind=0.0.0.0:2732
```
I also tried with **--preload** flag in above command

**Comment by agronholm** [comment] 2020-12-22 10:33
How can I reproduce this? What is this `views.py` you referenced but didn't provide?

**Comment by dineshgawali** [comment] 2020-12-22 10:44
In views.py file setting job as 
```
start_date_of_job = model_object.start_date
start_time = dates.strptime(model_object.start_time, '%I.%M %p').time()
start_datetime_of_job = dates.combine(start_date_of_job, start_time)
settings.scheduler.add_job(function_to_run, 'date', jobstore='redis', replace_existing=True,
    run_date=start_datetime_of_job, misfire_grace_time=None,
    id="start-" + str(model_object.id),
    args=[args list])
```

**Comment by christopherpickering** [comment] 2020-12-22 14:34
Hi, APScheduler will only work in a 1 worker gunicorn process.. otherwise you will have two confused schedulers running and a compromised job store.. which is why everyone is waiting for 4.0 :) 

I built an app using gunicorn as well, with a Redis job store. Our service had too much traffic for a single worker (plus w/ a single worker you have to wait until the jobs complete before anything can move on) so we split the app into three pieces - A GUI (with many workers), an API running apscheduler (with 1 worker), and another API running the jobs (with many workers). We have some very long running jobs (up to 15 minutes), and quite a bit of GUI traffic for monitoring the tasks.

With a three part process the GUI is always responsive, the task scheduler never "gets behind", or misses executions of other tasks because of one long running task, and the runner has enough horse power to run several giant tasks together.

**Comment by agronholm** [comment] 2020-12-22 15:04
Could you just make a zip file with a minimal runnable example that reproduces the problem, along with a list of dependencies (if other than apscheduler and gunicorn)? Strip out anything that isn't strictly necessary to reproduce the problem.

**Comment by agronholm** [comment] 2020-12-22 15:06
And yes, ensure that you can still reproduce the problem with just 1 worker.

**Comment by zackzhu730** [comment] 2021-01-05 09:28
> And yes, ensure that you can still reproduce the problem with just 1 worker.

Does the `1 worker` mean using `class BlockingScheduler` instead of `class BackgroundScheduler`?

**Comment by christopherpickering** [comment] 2021-01-05 14:42
@zackzhu730 - no, `BackgroundScheduler` will work just fine with `1 worker`. The comments about 1 worker are only referring to the gunicorn service.

When you start a gunicorn process running APScheduler you should specify `--workers 1` so from the initial question, it would be something like this:
```sh
/home/ubuntu/project/project_folder/venv/bin/gunicorn project.wsgi:application  --timeout 120 --workers 1 --threads=3 --bind=0.0.0.0:2732
```

When gunicorn starts up it will create a separate "live" instance of your project for each worker. This means you'll have several APSchedulers running against the same job store, which is not what v3.0 is designed to do, and will not reliably run jobs.

**Comment by zackzhu730** [comment] 2021-01-05 23:58
@christopherpickering , thank for your reply.

**Comment by agronholm** [comment] 2021-01-11 11:13
Seems this was settled, so I'll close the issue.

**Closed by agronholm** 2021-01-11 11:13 UTC

**Comment by scottwallacesh** [comment] 2024-04-10 07:33
As someone who recently ran into a similar issue to this, I found running Gunicorn with `--preload` resolved the problem when running APScheduler under Gunicorn with multiple workers.

With preloading, it only runs a single "thread" for the scheduled jobs.

**Comment by agronholm** [comment] 2024-04-10 07:57
Would that involve running multiple schedulers against the same data store?
