### ISSUE TITLE
Upgrading from apscheduler(3.0.1) to apscheduler(3.1.0)

### ISSUE THREAD

**Issue by anoopkhandelwal** [agronholm/apscheduler#141] opened 2016-05-04 11:21 UTC
Hi,
I am getting the traceback while upgrading it to 3.1.0
/home/myDir/Desktop/scheduler_lib/env/bin/python /home/myDir/Desktop/scheduler_lib/StartScheduler.py
Traceback (most recent call last):
  File "/home/myDir/Desktop/scheduler_lib/StartScheduler.py", line 10, in <module>
    from scheduler.RPCService import SchedulerJobFunctions
  File "/home/myDir/Desktop/scheduler_lib/scheduler/SchedulerJobs.py", line 4, in <module>
    from apscheduler.jobstores.base import JobLookupError
  File "/home/myDir/Desktop/scheduler_lib/env/local/lib/python2.7/site-packages/apscheduler/__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public'

Process finished with exit code 1

For more [refer](http://stackoverflow.com/questions/37025916/upgrading-apscheduler-from-3-0-1-to-3-1-0)

**Comment by agronholm** [comment] 2016-05-04 11:23
Another duplicate of #123.

**Closed by agronholm** 2016-05-04 11:23 UTC
Labels: duplicate
