### ISSUE TITLE
BackgroundScheduler is not working after few hours

### ISSUE THREAD

**Issue by Nayyaroddeen** [agronholm/apscheduler#515] opened 2021-05-28 17:25 UTC
I am using the django to build a reminders service
the current version of apscheduler=3.7.0

Issue: Scheduling and executing of jobs works fine for 10 hours of spinning the server. Post that we are able to add job but BackgroundScheduler is not able to execute the given function. I have enabled the logging but didn't find anything in logs

What could be the potential reason?
```python3
#creating a scheduler
scheduler = BackgroundScheduler(timezone=settings.TIME_ZONE)
scheduler.add_jobstore(DjangoJobStore(), "default")
if not scheduler.running:
    scheduler.start()

#adding job
 job = scheduler.add_job(send_reminder,
                                        trigger='date',
                                        next_run_time=str(date_time),
                                        args=[text])

#function to execute
def send_reminder(text, recruiter_id, company_id, application_id):
     print("something")
```

**Comment by agronholm** [comment] 2021-05-28 18:30
I'm surprised this works at all, since there is nothing in this script to keep the background scheduler running and the script would just exit.

You also seem to be using an unofficial job store which may also be a problem.

**Comment by agronholm** [comment] 2021-05-28 18:33
If you can give me a script that reproduces the problem using an official job store, I can investigate the problem.

**Comment by Nayyaroddeen** [comment] 2021-05-28 19:47
@agronholm yes, I copied parts of the script. I found there is an issue with threads flag --enable-threads for uWSGI https://apscheduler.readthedocs.io/en/latest/faq.html. I am experimenting with  https://gunicorn.org/, logs are coming properly. I will update the ticket accordingly.

**Comment by jjqi92** [comment] 2021-08-18 04:08
has the problem been solved? i had the same problem, and the log didn't have anything error or exception

**Comment by Nayyaroddeen** [comment] 2021-08-18 04:27
It happens due to mysql server disconnection. were you able to check it?

**Comment by agronholm** [comment] 2024-07-27 22:01
Closing as obsolete.

**Closed by agronholm** 2024-07-27 22:01 UTC
