### ISSUE TITLE
schedulers/base.py:156: RuntimeWarning: Got OperationalError: (1064, "You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by Galo1117** [agronholm/apscheduler#310] opened 2018-05-14 12:15 UTC
I used add_job when the SQL syntax was incorrect. After inserting two inserts (_binary_binary) inside the insert statement, there should normally be only one. Is there any problem with this? I tried the same problem with v3.5.1 v3.5.0 v3.4.0.

## Expected Behavior
![image](https://user-images.githubusercontent.com/38929628/39996666-dddc4764-57b2-11e8-9f06-3fe28c9f06a1.png)
INSERT INTO `django_apscheduler_djangojob` (`name`, `next_run_time`, `job_state`) VALUES ('sqlreview-1', '2018-05-15 22:11:52', _binary'\udc80\udc95\udc96\0\0\0\0\0\0}\udc94(\udc8c version\udc94K\udc8cfunc\udc94\udc8csql.sqlreview:execute_job\udc94\udc8c trigger\udc94\udc8capscheduler.triggers.date\udc94\udc8cDateTrigger\udc94\udc93\udc94)\udc81\udc94}\udc94(hK\udc8run_date\udc94\udc8datetime\udc94\udc8datetime\udc94\udc93\udc94C\n \udce24\0\0\0\udc94\udc8cpytz\udc94\udc8c_p\udc94\udc93\udc94(\udc8c\rAsia/Shanghai\udc94M\udc80pK\0\udc8cCST\udc94t\udc94R\udc94\udc86\udc94R\udc94ub\udc8executor\udc94\udc8c default\udc94\udc8c\rmax_instances\udc94K\udc8cmisfire_grace_time\udc94K\udc8cargs\udc94\udc8c1\udc94\udc8chttp://127.0.0.1:8000/detail/1/\udc94\udc86\udc94\udc8cid\udc94\udc8csqlreview-1\udc94\udc8c\rnext_run_time\udc94h\udc8coalesce\udc94\udc88\udc8ckwargs\udc94}\udc94\udc8cname\udc94\udc8cexecute_job\udc94u.'); 

## Current Behavior
![image](https://user-images.githubusercontent.com/38929628/39996721-0e58f464-57b3-11e8-94b1-3384776ecf31.png)
![image](https://user-images.githubusercontent.com/38929628/39996781-4030f2d4-57b3-11e8-8428-ea654f85311e.png)

INSERT INTO `django_apscheduler_djangojob` (`name`, `next_run_time`, `job_state`) VALUES ('sqlreview-11', '2018-05-15 17:15:01', _binary _binary'\udc80\udc95\udca1\0\0\0\0\0\0}\udc94(\udc8ckwargs\udc94}\udc94\udc8cmisfire_grace_time\udc94K\udc8executor\udc94\udc8cdefault\udc94\udc8coalesce\udc94\udc88\udc8cargs\udc94\udc8c11\udc94\udc8c&http://192.168.123.110:8080/detail/11/\udc94\udc86\udc94\udc8cid\udc94\udc8c
  sqlreview-11\udc94\udc8cfunc\udc94\udc8csql.sqlreview:execute_job\udc94\udc8ctrigger\udc94\udc8capscheduler.triggers.date\udc94\udc8c
                                                                                                                                          DateTrigger\udc94\udc93\udc94)}\udc94\udc92\udc94}\udc94(\udc8cversion\udc94K\udc8run_date\udc94\udc8datetime\udc94\udc8datetime\udc94\udc93\udc94C\n\udce2\0\0\0\udc94\udc8cpytz\udc94\udc8c_p\udc94\udc93\udc94(\udc8c\rAsia/Shanghai\udc94M\udc80pK\0\udc8cCST\udc94t\udc94R\udc94\udc86\udc94R\udc94ub\udc8c\rmax_instances\udc94K\udc8c\rnext_run_time\udc94h$hK\udc8cname\udc94\udc8c
                                                                                                  execute_job\udc94u.');

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/38929628/39996863-8284bd00-57b3-11e8-845b-803171047c30.png)

**Comment by agronholm** [comment] 2018-05-15 16:44
How am I supposed to reproduce the problem with that screenshot? And can you reproduce this without the Django job store? It is not my code and as such I am not responsible for its problems.

**Comment by weaming** [comment] 2018-11-03 09:41
My workmate reproduced using mysqlclient and pymysql, but the reason is unsure.

**Comment by agronholm** [comment] 2018-11-03 13:00
Can you offer any better way to reproduce this?

**Comment by agronholm** [comment] 2018-12-04 12:06
Closing as invalid since DjangoJobStore is not part of this project.

**Comment by agronholm** [comment] 2018-12-04 12:07
I suggest you create an issue in that project instead.

**Closed by agronholm** 2018-12-04 12:06 UTC
Labels: invalid
