### ISSUE TITLE
3.9.1 is not Python 2.7 compatible

### ISSUE THREAD

**Issue by jmath222** [agronholm/apscheduler#678] opened 2022-11-11 18:17 UTC
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1

### What happened?

apscheduler/util.py has a call to datetime.datetime.timestamp(), which does not exist in python 2.7. It looks like this was mistakenly introduced in 3.9.0.

### How can we reproduce the bug?

In a Python 2.7 environment, add a job using a CronTrigger.

**Comment by agronholm** [comment] 2022-11-11 18:37
Duplicate of https://github.com/agronholm/apscheduler/issues/666.

**Closed by agronholm** 2022-11-11 18:37 UTC
Labels: bug
