### ISSUE TITLE
skipped: maximum number of running instances reached (100)

### ISSUE THREAD

**Issue by ybbiubiubiu** [agronholm/apscheduler#644] opened 2022-07-18 08:13 UTC
**Describe the bug**
I encountered a problem when using flask-apschedule, I don't know if it is used in the wrong way or a bug:
When I have configured `'max_instances': 100` in the global configuration, after the service starts for a period of time, individual tasks with relatively high running frequency will often reach the threshold of 100, and an error message will be generated, which will cause subsequent tasks to fail to start normally. I have confirmed that those tasks are not tasks that take a long time. After looking at the source code, I am not sure whether _run_job_success (the task runs successfully) is called after the task ends and subtracted by 1.

**To Reproduce**

schduler_config.py
```
def config_scheduler(app):
    f = open("scheduler.lock", "wb")
    try:
        fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
        scheduler.init_app(app)
        with session_scope() as session:
            trigger(JobInfo.get_non_terminate_job(session), session)
        scheduler.add_job('0', add_task, trigger='interval', seconds=40)
        scheduler.start()
    except Exception as e:
        print(traceback.format_exc())
```

config.py
```
class Config(object):
    SCHEDULER_EXECUTORS = {
        'default': {'type': 'threadpool', 'max_workers': 30}
    }
    SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 100,
    }
    SCHEDULER_TIMEZONE = 'Asia/Shanghai'```


**Additional context**
```
2022/07/18 12:39:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:39:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:40:00] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "1216 (trigger: cron[hour='5-23', minute='0/10'], next run at: 2022-07-18 12:40:00 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:40:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:40:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:40:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:40:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:41:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:41:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:42:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:42:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:42:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:42:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:43:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:43:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:44:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:44:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:44:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:44:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:45:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:45:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:46:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:46:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:46:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:46:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:47:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:47:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:48:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:48:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:48:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:48:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:49:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:49:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:50:00] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "1216 (trigger: cron[hour='5-23', minute='0/10'], next run at: 2022-07-18 12:50:00 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:50:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:50:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:50:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:50:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:51:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:51:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:52:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:52:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:52:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:52:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:53:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:53:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:54:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:54:14 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:54:54] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:54:54 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:55:34] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:55:34 CST)" skipped: maximum number of running instances reached (100)
[2022/07/18 12:56:14] apscheduler.scheduler base.py _process_jobs 978 WARNING Execution of job "0 (trigger: interval[0:00:40], next run at: 2022-07-18 12:56:14 CST)" skipped: maximum number of running instances reached (100)
```

**Comment by dp24678** [comment] 2022-07-25 09:14
I also encountered this problem

**Comment by agronholm** [comment] 2022-07-25 09:20
Not helpful. And @ybbiubiubiu how am I supposed to reproduce the problem when you're not even showing the code for the scheduled job? It's not like I can just run the code you provided since it's missing the `add_task` function.

**Comment by ybbiubiubiu** [comment] 2022-07-25 09:28
> 
allright ..
I did not add the code of 'add_task' here because the specific code logic on my side is very simple and there are no other complicated operations.

**Comment by agronholm** [comment] 2022-07-25 09:28
So if you could provide me a runnable example that demonstrates the issue, then I can maybe help.

**Comment by ybbiubiubiu** [comment] 2022-07-25 09:33
> So if you could provide me a runnable example that demonstrates the issue, then I can maybe help.

ok  I'll write something similar here and I'll send it to you

**Comment by ybbiubiubiu** [comment] 2022-07-25 12:11
Hey  bro ,I took a look here and I can't directly provide a code that can run.
I can only simplify the code logic of add_task as follows, you can see the main code logic. In fact, it is very simple: job 0 actually polls regularly to obtain new tasks, and then adds the new tasks to the schduler through the API add_task. Then there are some data manipulations.

In addition, if I still can't troubleshoot the problem, I can only check it slowly through the code.
Thanks again! good luck
```
def add_task():
    DBSession = sessionmaker(engine)
    session = DBSession()
    job_infos = [{},{}]  # This variable is the task information obtained from the database, and the type is a map list
    for job in job_infos:
        try:
            # params: # Build Timing Information
            if job['trigger_type'] == TriggerType.cron.value:
                params = {"trigger":"cron","year":"*",...:...}
            elif job['trigger_type'] == TriggerType.date.value:
                params = {'run_date': "xxxxxx",'trigger': 'date'}
            elif job['trigger_type'] == TriggerType.interval.value:
                params = {"trigger":"interval", "seconds":222,...:...}
            else:
                continue
            params['args'] = [job['id']]
            scheduler.add_job(str(job['id']), job_executor, **params)
            # update data into db
        except Exception as e:
            # update data into db
            pass


def job_executor(job_id):
    DBSession = sessionmaker(engine)
    session = DBSession()
    job = JobInfo.get_info_by_id(job_id, session) # job is a dict of info
    url, data, job_id, method = job['task_url'], job.get('params'), job['id'], job['job_type']
    if method == JobType.get.value:
        response_content, status = url_get_request(url, data)  # http get 
    elif method == JobType.post.value:
        response_content, status = url_post_str_request(url, data)  # http post

    else:
        # alert
        return
    JobResult.save_obj({'job_id': job_id, 'result': str(response_content), 'status': status}, session)
    job_update_dict = {'last_execute_result': str(response_content), 'last_execute_status': status}
    if job['trigger_type'] == TriggerType.date.value:
        job_update_dict['status'] = JobStatus.end.value
    JobInfo.update_job(job_id, {'last_execute_result': str(response_content), 'last_execute_status': status},
                       session)
```

**Comment by ybbiubiubiu** [comment] 2022-07-25 12:34
Also I have a question, is this global limit for all pending tasks? It is not the task limit of the same id. Does it mean that if the executor reaches 100 tasks to be executed, other new tasks will not be executed?
```
SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 100,
    }
```

**Comment by agronholm** [comment] 2022-07-25 15:45
> Also I have a question, is this global limit for all pending tasks? It is not the task limit of the same id. Does it mean that if the executor reaches 100 tasks to be executed, other new tasks will not be executed?
> 
> ```
> SCHEDULER_JOB_DEFAULTS = {
>         'coalesce': False,
>         'max_instances': 100,
>     }
> ```

No, it's not a global limit. It's a per-job default. And is there a reason you're setting `coalesce` to `False`? Your use case doesn't seem to warrant that., at least for `add_task()`.

If you're hitting the 100 concurrent job limit, then it means your jobs are not completing. You need to first figure out **why**.

**Comment by ybbiubiubiu** [comment] 2022-07-26 01:57
I also wonder if job 0 has not been completed, but the logic of job 0 is really simple, and I can't think of a situation where it is not completed over time. Yesterday, I added a time-consuming log to `add_task`. At present, the execution speed is very fast and far from the task interval. Then when the problem occurs later, I can see whether the time-consuming exceeds the execution interval of the task.

**Comment by agronholm** [comment] 2024-05-11 10:33
Closing as obsolete.

**Closed by agronholm** 2024-05-11 10:33 UTC
