### ISSUE TITLE
doubt about the job Event Listener

### ISSUE THREAD

**Issue by wck821829906** [agronholm/apscheduler#333] opened 2018-08-31 07:31 UTC
@agronholm , Hi , I am so upset and doubtful why the job event listener triggered twice sometimes for one job.
![listener](https://user-images.githubusercontent.com/17002975/44898921-ebc00480-ad32-11e8-9444-7029eb9a455c.png)

**Comment by agronholm** [comment] 2018-08-31 07:43
I don't see a problem here, at least from what I see in the screenshot. A SUBMITTED event is fired every time the job has been submitted to the executor and EXECUTED is fired every time the job has finished its run on the executor. If you feel something is going wrong, I suggest you show me a self contained example that reproduces the problem.

**Comment by wck821829906** [comment] 2018-08-31 08:26
@agronholm , It seems that I have not expressed my problem clearly, my question is for one certain job, from my understanding, the submitted event should be fired only one time regularly when the job triggered. but actually, it fired sometimes twice, and one time sometimes. it seems has no order.

![listener1](https://user-images.githubusercontent.com/17002975/44901668-9c7dd200-ad3a-11e8-9fa9-0fa87fb19d8b.png)

**Comment by agronholm** [comment] 2018-08-31 11:57
Could you provide me a self contained script which reproduces the problem? Otherwise I'm just guessing here.

**Comment by agronholm** [comment] 2018-08-31 13:38
Looking at your screenshot, it looks like you have a matching number of `start` and `end` events. Could it be that it's being submitted to the executor twice somehow? Logging in itself does not seem to be the problem.

**Comment by agronholm** [comment] 2021-01-17 16:10
No answer in well over 2 years – closing.

**Closed by agronholm** 2021-01-17 16:10 UTC
