### ISSUE TITLE
[v4.0.0a4] Setting `timezone` in `CalendarIntervalTrigger` loops forever

### ISSUE THREAD

**Issue by bmeares** [agronholm/apscheduler#912] opened 2024-05-13 21:03 UTC
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

v4.0.0a4

### What happened?

Adding the `timezone` keyword argument to `CalendarIntervalTrigger` hangs when calling `next()`. This does not occur when defaulting to the local timezone.

### How can we reproduce the bug?

```python
from datetime import datetime, timezone
from apscheduler.triggers.calendarinterval import CalendarIntervalTrigger

start_dt = datetime(2024, 5, 1, tzinfo=timezone.utc)
monthly_trigger = CalendarIntervalTrigger(months=1, start_date=start_dt)
monthly_trigger.next()
# datetime.datetime(2024, 5, 1, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='America/New_York'))

monthly_trigger = CalendarIntervalTrigger(months=1, start_date=start_dt, timezone=start_dt.tzinfo)
monthly_trigger.next()
# Hangs in a loop
```

**Comment by agronholm** [comment] 2024-05-13 21:46
Duplicate of #897, already fixed in `master` via b5dfbedc3945fa7e15f5feda490e98888e508f2f.

**Closed by agronholm** 2024-05-13 21:46 UTC
Labels: bug
