### ISSUE TITLE
Cannot add job once scheduler has started

### ISSUE THREAD

**Issue by radiantone** [agronholm/apscheduler#557] opened 2021-10-13 09:36 UTC
**Describe the bug**
Cannot add job once scheduler has started

**To Reproduce**
Add a job after scheduler has started

**Expected behavior**
I want to add jobs dynamically and have the scheduler recognize jobs in the jobstore at any time

**Additional context**
Version 3.7

**Comment by agronholm** [comment] 2021-10-30 23:12
This works for everybody else just fine. Please provide a code sample that reproduces the problem you're seeing.

**Comment by LasseMoench** [comment] 2021-11-29 10:21
I am perhaps experiencing a similar thing:
I am using APScheduler with Flask, using the BackgroundScheduler. When I add a (one-time) job dynamically using the add_job method, the wakeup time is not recalculated and the job will not start as expected. If any other job runs before the job is to be executed, the wakeup time gets recalculated correctly. For now, my workaround is to just schedule an empty job to run once per minute.

**Comment by agronholm** [comment] 2021-11-29 10:24
Have you read the [FAQ](https://apscheduler.readthedocs.io/en/3.x/faq.html#how-do-i-use-apscheduler-in-a-web-application) and/or the [troubleshooting](https://apscheduler.readthedocs.io/en/3.x/userguide.html#troubleshooting) instructions?

**Comment by LasseMoench** [comment] 2021-11-29 10:30
I am using FlaskAPscheduler and I have read both FAQ and troubleshooting. I have activated the debug logging, which has led me to believe that the job is not run because no wakeup is scheduled. I am sorry that I can not provide a code example using only APscheduler at the moment, I do not expect you to investigate this until I find the time to provide a small example.

**Comment by radiantone** [comment] 2021-11-29 10:43
Yeah. Apscheduler doesnt seem to properly allow jobs to be added or scheduled once its started. I will also work up an example becaise this is a basic and obvious need.

**Comment by agronholm** [comment] 2021-11-29 10:51
It certainly does. Lots of users are relying on this functionality.

**Comment by agronholm** [comment] 2022-08-17 18:11
No reproduction instructions were ever provided, so I'm closing this.

**Closed** 2022-08-17 18:11 UTC
