### ISSUE TITLE
Memory not being cleared within Docker container after job is finished.

### ISSUE THREAD

**Issue by sam-lakestar** [agronholm/apscheduler#600] opened 2022-03-01 10:38 UTC
**BUG**
When running compute and memory intensive jobs, memory is not cleared after a scheduled job is run. 
This is causing Docker containers to eventually die with a 137 error. 
Running the same function outside of APScheduler does not show the same behaviour.

**SETUP**
Flask application with APBackground Scheduler running on EC2 instance. 
Used for ML model deployment and retraining. 
Retraining is scheduled once per week via apscheduler.triggers.cron.CronTrigger

**EXAMPLE**
```
from flask import Flask
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from models import retrain_model

app = Flask(__name__)

@app.route('/')
def home():
    return "Home Page"

if __name__ == "__main__":
    scheduler = BackgroundScheduler()
    scheduler.add_job(retrain_model, CronTrigger.from_crontab("0 0 * * 1"), id="retrain", replace_existing=True)  # Compute and memory intense function
    scheduler.start()
    app.run("0.0.0.0", debug=True)
```

**EXPECTED BEHAVIOUR**
Memory to return to same state as before running the job. At rest, flask application is using approximately 214mb. Every time the scheduled job is run, the memory usage increases by approximately 500mb.

**Additional Information**
Have attempted multiple different solutions and none seem to work:
https://stackoverflow.com/questions/46301647/memory-usage-not-getting-lowered-even-after-job-is-completed-successfully

**Comment by agronholm** [comment] 2022-03-01 10:59
Have you used a memory profiler to find out where the memory goes?

**Comment by agronholm** [comment] 2022-03-03 12:50
Would it be possible to construct a self contained example that demonstrates the issue? Otherwise I don't even know where to start.

**Comment by Ludo15** [comment] 2022-06-01 21:02
I have the same issue using apscheduler 3.9.1,

In my case, I'm using the ProcessPoolExecutor and each run's memory isn't cleared.
Ex: (Assumes max_workers=1) If a job is runned and takes 3GB of memory, on the next run, the memory will be 6GB and will add up until there's no memory on my computer.

By looking at the code (correct me if i'm wrong), seems this issue is caused by concurrent.futures.ProcessPoolExecutor. Looking at the documentation, it only frees resources when the shutdown method is called:  https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown

I think the usecase of using concurrent.futures.ProcessPoolExecutor is different than with apscheduler:
- I use apscheduler for scheduling recurring jobs (could be running weeks, months, maybe years...)
- concurrent.futures.ProcessPoolExecutor seems to be tailored to multiprocess finite tasks and then shutdown

More info on the answer of this link:
https://stackoverflow.com/questions/56237493/how-to-make-tasks-in-processpoolexecutor-behave-like-daemon-process

Is there any alternatives in apsscheduler that would free resources after each job?

**Comment by agronholm** [comment] 2022-06-01 21:04
Can you provide code that reproduces the problem?

**Comment by alexbigi** [comment] 2022-08-08 17:47
> Can you provide code that reproduces the problem?

I have the same issue using apscheduler 3.9.1 too on AsyncIOScheduler with sqlalchemy
my code:
`
jobstores = {
    'default': SQLAlchemyJobStore(url='sqlite:///aps_scheduler_auth_jobs.sqlite')
}
Scheduler = AsyncIOScheduler(jobstores=jobstores, timezone=str(tzlocal.get_localzone()))
DATABASE_URL = "postgresql+asyncpg://user:pass@localhost/database"
engine = create_async_engine(DATABASE_URL, echo=False)
Base = declarative_base()
async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

async def subscription_checker():
    SLEEP_DURATION = 5e-3  # 5 ms sleep
    print(">>> expired subscription checker started...")
    async with async_session() as session:
        users_list = await service.get_all_users(session)
        for index, obj in enumerate(users_list):
            # print(f"{index}/{len(users_list)}")
            await subscription_expired_checker(session, obj, obj.uid, config, async_session)
            await asyncio.sleep(SLEEP_DURATION)
    print(">>> expired subscription checker ended...")
    sys.stdout.flush()


def init():
    print(">>> cron service started...")
    Scheduler.start()
    Scheduler.add_job(subscription_checker, 'cron', hour="14", id="subscription_checker", replace_existing=True)
    sys.stdout.flush()


if __name__ == "__main__":
    init()
    try:
        asyncio.get_event_loop().run_forever()
    except (KeyboardInterrupt, SystemExit):
        pass
`
can u help me?

**Comment by agronholm** [comment] 2022-08-11 09:23
I don't know how to convey to you that I need code that I can actually run myself – a minimal script that still reproduces the problem. Memory leaks are extremely hard to debug, so I need all the information I can possibly get. I will not spend my time on a wild goose chase.

**Comment by Sammo98** [comment] 2022-08-11 09:37
@agronholm 

I have investigated this a lot recently and have come to the conclusion that it's an issue flask/docker/ubuntu issue where memory is not freed.

https://www.paulsprogrammingnotes.com/2014/10/large-dictionaries-not-released-from.html?showComment=1483516233443#c3352147816385844344

I think this issue can be closed as I do not believe it to be related to apscheduler.

**Comment by agronholm** [comment] 2022-08-11 09:51
Gotcha – thanks for letting me know!

**Comment by danerlt** [comment] 2022-09-08 06:42
@agronholm 
I have the same issue using apscheduler 3.9.1,
my code is:
```
import datetime
import os
from functools import wraps

import psutil
import tensorflow as tf
import numpy as np

from tensorflow import keras
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.interval import IntervalTrigger


def memory(func):
    @wraps(wrapped=func)
    def wrapper(*args, **kwargs):
        try:
            memo = psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024
            print(f'before call funcion：{func.__name__}, memory used：%.4f MB' % memo)
            result = func(*args, **kwargs)
            memo = psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024
            print(f'after call funcion：{func.__name__} memory used：%.4f MB' % memo)
            return result
        except Exception as e:
            print("memory error: e")
            raise e

    return wrapper


@memory
def bar():
    xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
    ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

    model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
    model.compile(optimizer='sgd', loss='mean_squared_error')
    # begin train , 5000 times
    model.fit(xs, ys, epochs=5000, verbose=0)
    # predict
    print(model.predict([10.0]))


def task():
    jobstores = {
        'default': SQLAlchemyJobStore(url='sqlite:///test.sqlite')
    }
    scheduler = BlockingScheduler(jobstores=jobstores)
    trigger = IntervalTrigger(seconds=10, start_date=datetime.datetime.now())
    scheduler.remove_all_jobs()
    scheduler.add_job(bar, trigger=trigger, id="job", coalesce=True, replace_existing=True, max_instances=1)
    scheduler.start()


if __name__ == '__main__':
    task()

```
I had 283MB of RAM when I ran it for the first time,After running for a while the memory increased to 428 MB.

The printout log is as follows:
```
before call funcion：bar, memory used：283.0195 MB
2022-09-08 14:36:24.435041: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
1/1 [==============================] - 0s 161ms/step
[[18.999987]]
after call funcion：bar memory used：314.9570 MB
before call funcion：bar, memory used：314.9727 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：323.3320 MB
before call funcion：bar, memory used：323.3516 MB
1/1 [==============================] - 0s 54ms/step
[[18.999987]]
after call funcion：bar memory used：330.7969 MB
before call funcion：bar, memory used：330.8242 MB
1/1 [==============================] - 0s 47ms/step
[[18.999987]]
after call funcion：bar memory used：338.7656 MB
before call funcion：bar, memory used：338.7812 MB
1/1 [==============================] - 0s 53ms/step
[[18.999987]]
after call funcion：bar memory used：341.7031 MB
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001B11586EAF8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
before call funcion：bar, memory used：341.7227 MB
1/1 [==============================] - 0s 47ms/step
[[18.999987]]
after call funcion：bar memory used：349.6406 MB
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001B11586E9D8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
before call funcion：bar, memory used：349.6602 MB
1/1 [==============================] - 0s 52ms/step
[[18.999987]]
after call funcion：bar memory used：356.6953 MB
before call funcion：bar, memory used：356.7109 MB
1/1 [==============================] - 0s 48ms/step
[[18.999987]]
after call funcion：bar memory used：363.5078 MB
before call funcion：bar, memory used：363.5273 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：366.5703 MB
before call funcion：bar, memory used：366.5859 MB
1/1 [==============================] - 0s 46ms/step
[[18.999987]]
after call funcion：bar memory used：372.7344 MB
before call funcion：bar, memory used：372.7344 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：380.2188 MB
before call funcion：bar, memory used：380.2227 MB
1/1 [==============================] - 0s 51ms/step
[[18.999987]]
after call funcion：bar memory used：382.7070 MB
before call funcion：bar, memory used：382.7070 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：389.6875 MB
before call funcion：bar, memory used：389.6875 MB
1/1 [==============================] - 0s 48ms/step
[[18.999987]]
after call funcion：bar memory used：395.8945 MB
before call funcion：bar, memory used：395.8984 MB
1/1 [==============================] - 0s 53ms/step
[[18.999987]]
after call funcion：bar memory used：397.6875 MB
before call funcion：bar, memory used：397.6875 MB
1/1 [==============================] - 0s 48ms/step
[[18.999987]]
after call funcion：bar memory used：403.0977 MB
before call funcion：bar, memory used：403.0977 MB
1/1 [==============================] - 0s 47ms/step
[[18.999987]]
after call funcion：bar memory used：409.6211 MB
before call funcion：bar, memory used：409.6250 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：417.1680 MB
before call funcion：bar, memory used：417.1719 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：419.9141 MB
before call funcion：bar, memory used：419.9141 MB
1/1 [==============================] - 0s 48ms/step
[[18.999987]]
after call funcion：bar memory used：425.8164 MB
before call funcion：bar, memory used：425.8320 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：431.7891 MB
before call funcion：bar, memory used：431.7891 MB
1/1 [==============================] - 0s 47ms/step
[[18.999987]]
after call funcion：bar memory used：434.3984 MB
before call funcion：bar, memory used：434.3984 MB
1/1 [==============================] - 0s 45ms/step
[[18.999987]]
after call funcion：bar memory used：418.5781 MB
before call funcion：bar, memory used：418.6992 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：419.7070 MB
before call funcion：bar, memory used：419.7070 MB
1/1 [==============================] - 0s 49ms/step
[[18.999987]]
after call funcion：bar memory used：421.5586 MB
before call funcion：bar, memory used：421.5586 MB
1/1 [==============================] - 0s 48ms/step
[[18.999987]]
after call funcion：bar memory used：422.8789 MB
before call funcion：bar, memory used：422.8789 MB
1/1 [==============================] - 0s 56ms/step
[[18.999987]]
after call funcion：bar memory used：424.0312 MB
before call funcion：bar, memory used：424.0312 MB
1/1 [==============================] - 0s 53ms/step
[[18.999987]]
after call funcion：bar memory used：425.7695 MB
before call funcion：bar, memory used：425.7695 MB
1/1 [==============================] - 0s 50ms/step
[[18.999987]]
after call funcion：bar memory used：428.1172 MB
before call funcion：bar, memory used：428.1172 MB
```

**Comment by frankiedrake** [comment] 2022-12-26 10:19
I have the same problem. I am able to get memory freed, running required code as a separate python script, e.g.
```
def job():
    subprocess.call(['python', 'standalone_runner.py'])


scheduler = BlockingScheduler()
scheduler.add_job(func=job,
                  trigger='interval',
                  id='each_5_minutes',
                  minutes=5,
                  misfire_grace_time=30,
                  next_run_time=datetime.now())
scheduler.start()
```

But what is strange, is that the problem appears only on stage/prod env (which is set by devops), running code with Docker on my local machine works just fine (I tried to reproduce the environment closer to a stage/prod as much as I can).

**Comment by agronholm** [comment] 2022-12-26 14:48
Do any one of you have any proof that this is an apscheduler problem? Like, have you tried running the same function over and over in a loop and verified that memory use does not grow?

**Comment by frankiedrake** [comment] 2022-12-27 15:32
> Do any one of you have any proof that this is an apscheduler problem? Like, have you tried running the same function over and over in a loop and verified that memory use does not grow?

Sorry @agronholm, I didn't mean that the problem is with apscheduler, I just noticed that it's related to it. As for me, I figured out that all heavy and high-resource consumable objects should be created in the job itself, not outside it, also better to start the job as a separate process. This way i seemed to solve my problem

**Comment by woalk** [comment] 2023-03-24 13:29
I have observed the same problem with [UnleashClient](https://github.com/Unleash/unleash-client-python), which internally uses APScheduler: Memory usage will continuously increase until the container is out of memory.

I have then created a minimal example that demonstrates the problem:

<details>
<summary><b>Example code using APScheduler (click to expand)</b></summary>

**`main.py`**
```py
""" Test for memory leaks with APScheduler """
import os
import time
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
import psutil

print(f"PID: {os.getpid()}, {os.getppid()}")
process = psutil.Process(os.getpid())
MEMORY = 0

EXECUTOR_NAME = "exec"
executor = ThreadPoolExecutor()
scheduler = BackgroundScheduler(executors={EXECUTOR_NAME: executor})

scheduler.start()


def job_func():
    """ Consume 512 MB RAM """
    global MEMORY
    MEMORY = process.memory_info().rss
    arr = bytearray(512000000)
    if arr:
        time.sleep(0.01)


def memory_func():
    """ Print memory usage """
    print(f"{'{:5.3f}'.format(MEMORY / 1000)} KB")


scheduler.add_job(job_func,
                  trigger=IntervalTrigger(
                      seconds=0.6,
                      jitter=0,
                  ),
                  executor=EXECUTOR_NAME)
scheduler.add_job(memory_func,
                  trigger=IntervalTrigger(
                    seconds=10,
                    jitter=0
                  ),
                  executor=EXECUTOR_NAME)

while True:
    pass
```

**`requirements.txt`**
```py
APScheduler==3.10.1
psutil==5.9.4
```
</details>

Running this for a couple minutes on my machine with Python 3.10.9, Ubuntu 22.04.2, you can observe the average memory used by the `python3` process continuously rising:

<details>
<summary><b>Log output (click to expand)</b></summary>

```
29511.680 KB
29515.776 KB
29536.256 KB
29540.352 KB
29540.352 KB
29540.352 KB
29540.352 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29544.448 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29552.640 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
29560.832 KB
```

While I have not run this over multiple hours, it suggests that it keeps rising and is therefore in fact the same problem as I and multiple others have observed in Docker containers.
</details>

While the same function run in a loop without APScheduler does not increase the average process memory at all.

<details>
<summary><b>Example without APScheduler (click to expand)</b></summary>

**`main.py`**
```py
""" Test for memory leaks with APScheduler """
import os
import time
import psutil

print(f"PID: {os.getpid()}, {os.getppid()}")
process = psutil.Process(os.getpid())
MEMORY = 0

def job_func():
    """ Consume 512 MB RAM """
    global MEMORY
    MEMORY = process.memory_info().rss
    arr = bytearray(512000000)
    if arr:
        time.sleep(0.01)


def memory_func():
    """ Print memory usage """
    print(f"{'{:5.3f}'.format(MEMORY / 1000)} KB")


x = 0
while True:
    job_func()
    x += 1
    if x > 10:
        memory_func()
        x = 0
```

Log output:
```
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
12709.888 KB
...
```
</details>

Adding `psutil` is of course optional and is just used to easily observe memory usage. The memory usage rising also happens without it.

Any ideas what could be causing this or how to work around it?

**Comment by agronholm** [comment] 2023-03-24 14:29
To simplify this, will `BlockingScheduler` also produce the same results? `while True: pass` is not kosher.

**Comment by woalk** [comment] 2023-03-24 14:53
I have now tried running the script both with

- `while True: pass` replaced with `input("press enter to exit")` and
- using `BlockingScheduler` instead of `BackgroundScheduler`

and in both cases, I still see the same memory behaviour.

**Comment by agronholm** [comment] 2023-03-24 22:22
I ran the script about the same amount of time, and it topped out at 25366.528 KB. Frankly, I don't see any constant growth in memory use here. Initially the thread pool will max out its workers, and that causes some memory use increase, but after that, it stays constant.

**Comment by woalk** [comment] 2023-03-25 09:09
Hm, so whatever we are observing in our containers, must be something else. I'll keep looking. Thank you.

**Closed** 2023-08-12 21:24 UTC

**Comment by CodingJzy** [comment] 2023-11-02 01:28
I also encountered a situation where I experienced a 100% increase and did not reclaim memory overnight.
I have the same code, Windows will not have any issues, but it will appear as soon as it reaches the Docker container. The system is Ubuntu 18, Python version 3.7. I also tried testing and wrote a simple demo,. Of course, I haven't tested as much. I hope you can test it. I have tested that scheduler calls can cause memory expansion, but ordinary functions don't. I'm not sure if starting processes and threads will cause it


`
import time


def cal():
    n = 0
    while 1:
        print("log...: ", n)
        b = [2] * (2 * 10 ** 7)
        n += 1
        if n == 3:
            break
    print("end...")


if __name__ == '__main__':
    time.sleep(3)
    print("启动。。。")
    cal()
    print("sleep ...")
    time.sleep(100)

`

![image](https://github.com/agronholm/apscheduler/assets/44855157/a9977492-64dc-481e-9457-ad680e72f4d4)
![image](https://github.com/agronholm/apscheduler/assets/44855157/91492718-a343-4b9c-8475-cd7a9a01eca6)

**Comment by agronholm** [comment] 2023-11-02 07:13
If you want to report new findings, please do so in a new issue. I'm also not going to investigate unless you can give me simple means to reproduce the problem locally.
