### ISSUE TITLE
Bug in handling dst transitions

### ISSUE THREAD

**Issue by backbord** [agronholm/apscheduler#116] opened 2016-03-28 10:39 UTC
Hi Alex,
unfortunately, the DST issue #115 is not fully closed.

After testing around (see comments
- https://github.com/agronholm/apscheduler/issues/115#issuecomment-202095754 hitting skipped hours
- https://github.com/agronholm/apscheduler/issues/115#issuecomment-202326483 hitting repeated hours
- https://github.com/agronholm/apscheduler/issues/115#issuecomment-202334893 more untested tests/use utc + trial and error

), I am dissapointed to not have come up with an elegant solution but only with more failing test cases.

I'll have another go at the problem (along the lines of https://github.com/agronholm/apscheduler/issues/115#issuecomment-202334893 use utc + trial and error) when I find the time.

Best regards,
Tim

**Comment by agronholm** [comment] 2016-03-28 10:46
Duplicate of #115.

**Closed by agronholm** 2016-03-28 10:46 UTC
Labels: duplicate

**Comment by agronholm** [comment] 2016-03-28 10:53
Those failing test cases make absolutely no sense:

- In the "repeat_hour_a" you create a schedule that runs every 30 minutes and "now" is set to 12:00. Then you somehow expect the next scheduled time to be 08:00 the same date?!?
- "repeat_hour_b" is the same as the previous, only with an ineffectual dst setting (the value only makes sense within the repeated hour during the switch from DST to winter time)
- "absolute_skipped_hour" tests that the hour is skipped when switching to winter time from DST, but that's when an hour is repeated, not skipped.
- "interval_skipped_hour" falls victim to the same misconception as the previous test

**Comment by backbord** [comment] 2016-03-28 11:06
Yes, the times are not correct. I seem to have pressed "comment" before I was really done. Wait, I'll fix them. (When I'm back at my development machine, I'll look into the problem a bit more.)

Did you get the gist of the problem?

**Comment by agronholm** [comment] 2016-03-28 11:36
I'm not sure. I haven't yet been able to produce a test case that would go against the [documentation](http://apscheduler.readthedocs.org/en/latest/modules/triggers/cron.html#daylight-saving-time-behavior) on Cron Trigger's DST handling.

**Comment by backbord** [comment] 2016-03-29 07:15
Today, I got to fix my tests and run them properly. I agree, your documentation says
> If your schedule would have the job executed on either one of these [DST switching] periods, it may execute more often or less often than expected. This is not a bug. If you wish to avoid this, either use a timezone that does not observe DST, for instance UTC. Alternatively, just find out about the DST switch times and avoid them in your scheduling.
and my tests confirm that behaviour of the CronTrigger not giving all expected firing times on the DST change in autumn: firing times that fall into the repeated period may be lost.
So yes, the behaviour does indeed agree with your documentation. :-)

Let's leave it at that. For all I know and tested, the bug that started the discussion is closed.
I'll go and see if monkey patching the behaviour to also fire at repeated times is really necessary for my use case.

Thanks and keep up the good work!
Tim
