### ISSUE TITLE
How do I turn off this log display？？？

### ISSUE THREAD

**Issue by zxiaozhou** [agronholm/apscheduler#432] opened 2020-04-29 01:53 UTC
## Detailed Description

How do I turn off this log display？？？My log has been adjusted to info, but it still shows。
The full length of this is not useful for me to record. I don't want to show this at all
![image](https://user-images.githubusercontent.com/62740686/80554212-fb5b8900-89fe-11ea-9179-e4ffba59cc6e.png)
The default of the original framework is info, which makes it impossible to show it without showing it
![image](https://user-images.githubusercontent.com/62740686/80554278-32ca3580-89ff-11ea-8462-77f76bf109b4.png)

**Comment by agronholm** [comment] 2020-04-29 05:21
As this issue tracker is only for reporting bugs, I'm closing this ticket. Please refer to the [User Guide](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help) for the proper venues to get assistance with APScheduler.

**Closed by agronholm** 2020-04-29 05:21 UTC

**Comment by zxiaozhou** [comment] 2020-04-29 05:49
@agronholm 
But these two default log is info, I can't change the source

**Comment by agronholm** [comment] 2020-04-29 06:03
It is not a bug. Contact me via the proper venue (Gitter or StackOverflow) and I can try to help you.

**Comment by zxiaozhou** [comment] 2020-04-29 06:11
@agronholm 
The apscheduler log to the error is fixed, but it's not good
