### ISSUE TITLE
AsyncIOScheduler listener doesn't work with async event function

### ISSUE THREAD

**Issue by 4n1qz5skwv** [agronholm/apscheduler#638] opened 2022-06-21 04:56 UTC
**To Reproduce**
```python
import asyncio

from apscheduler.events import EVENT_SCHEDULER_STARTED
from apscheduler.schedulers.asyncio import AsyncIOScheduler

scheduler = AsyncIOScheduler(job_defaults={'coalesce': True, 'max_instances': 1})


async def my_listener(event):
    print('Yea......................')


scheduler.add_listener(my_listener, EVENT_SCHEDULER_STARTED)

scheduler.start()
asyncio.get_event_loop().run_forever()
```

**Expected behavior**
print -> `Yea......................` on scheduler start.

**Actual behaviour**
no print. just warning...
```
RuntimeWarning: coroutine 'my_listener' was never awaited
  cb(event)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Version**
`APScheduler==3.9.1`

**Comment by agronholm** [comment] 2022-06-21 05:21
This is not a bug, it's a shortcoming of the old design which has been fixed in the upcoming v4.0 (master).

**Closed by agronholm** 2022-06-21 05:21 UTC

**Comment by agronholm** [comment] 2022-06-21 07:21
Watch #465 for updates.
