### ISSUE TITLE
Standard tzinfo is not enough for apscheduler

### ISSUE THREAD

**Issue by b4stien** [agronholm/apscheduler#384] opened 2019-07-25 10:26 UTC
## Expected Behavior

`apscheduler` should work with `next_run_time` specified with standard `tzinfo`.

## Current Behavior

`apscheduler` crashes.

## Steps to Reproduce

```
from datetime import datetime, timedelta
from dateutil.tz import tzutc

next_run_time = datetime.now(tzutc()) + timedelta(seconds=30)
scheduler.add_job(
    lambda: print("Hello"), trigger=IntervalTrigger(minutes=1), next_run_time=next_run_time
)

```

## Context (Environment)

`apscheduler` works only with `pytz` objects, the problematic call is there : https://github.com/agronholm/apscheduler/blob/18b50d9ee9ff14e816b557e34d7d3abc861d57e5/apscheduler/triggers/interval.py#L66

If `next_fire_time` is not stamped with a `pytz.tzinfo.BaseTzInfo`, it crashes.

`self.timezone` is a `pytz` object, `normalize()` is a `pytz` function which expects a `pytz.tzinfo.BaseTzInfo` as argument (see https://github.com/stub42/pytz/blob/master/src/pytz/tzinfo.py#L66) with an internal (and absent from the standard `tzinfo`) `_utcoffset` there : https://github.com/stub42/pytz/blob/master/src/pytz/tzinfo.py#L252.

**Comment by agronholm** [comment] 2019-07-25 10:29
Where did you get the idea that apscheduler should work with any tzinfo? The dependency on pytz timezones is mentioned in the documentation. This is specifically since only pytz timezones have the `localize()` and `normalize()` methods as you mentioned yourself.

**Comment by b4stien** [comment] 2019-07-25 10:31
From the signature there for instance : https://github.com/agronholm/apscheduler/blob/18b50d9ee9ff14e816b557e34d7d3abc861d57e5/apscheduler/triggers/interval.py#L22.

Also there : https://github.com/agronholm/apscheduler/blob/7e78cad90ce080825c46de8967d9573e9fc86353/apscheduler/job.py#L32

"It works with datetime, but if you specify a `tzinfo` it must comes from `pytz`" is not very explicit.

**Comment by b4stien** [comment] 2019-07-25 10:39
To precise my comment (and issue) the fact that when giving explicit timezone to apscheduler you have to use `pytz` stuff is not a problem (and I apologize for not reading the docs about it - tbh I don't use this feature).

My issue is that my standard datetimes with standard tzinfo does not work when given to `next_run_time`.

**Comment by agronholm** [comment] 2019-07-25 10:42
Indeed this is something that should be validated earlier – at least when the job is being added. The fact that it crashes later is quite unfortunate.

I am currently working on APScheduler 4.0 and this sample snippet will not work with it but I will make sure that the time zone requirement is properly documented and validated going forward.

**Comment by kaos** [comment] 2019-07-26 18:09
Wouldn't it be feasible to convert a standard tzinfo into a pytz one automatically.. ?

**Comment by agronholm** [comment] 2019-07-27 16:21
> Wouldn't it be feasible to convert a standard tzinfo into a pytz one automatically.. ?

While technically any tzinfo could be converted into a pytz `FixedOffset` timezone, the results could be unexpected when the timezone is used for time arithmetic. A user might pass a start time with a time zone that does have DST rules. Then they will wonder why their jobs are scheduled one hour early or late once the DST switch point is crossed. So I am not sure if this is a good idea.

**Comment by b4stien** [comment] 2019-07-29 09:23
There are two closely related but different subjects : the timezones we give directly to apscheduler and the timezones attached to datetimes we give to apscheduler.

### Timezone gave to apscheduler

This is IMO a documentation issue. It would be marginally better to be able to use "standard" tzinfo but as you explicitely pass timezone objects to apscheduler in that case, it is reasonable to ask the user to use pytz stuff.

### Timezone attached to datetime gave to apscheduler

This is IMO a code/logic issue. Standard's `datetime.datetime` are widespread in Python codebase as are libraries dealing with timezone logic (https://github.com/dateutil/dateutil, https://github.com/crsmithdev/arrow, https://github.com/sdispater/pendulum, ...) generating standard's `datetime.tzinfo`. It looks like a tough deal for those codebases to impose the use of `pytz.tzinfo` in all the codebase to generate compatible datetimes.

I'm under the impression that we could convert the datetime's given tzinfo to a pytz one at:

https://github.com/agronholm/apscheduler/blob/18b50d9ee9ff14e816b557e34d7d3abc861d57e5/apscheduler/util.py#L124

For those timezone-aware datetimes I don't think there is an issue with the conversion as it's a "perfectly identified moment in time", DST does not intervene there.

Let me know if I can be of any help for a PR on those subjects if the approaches looks fine to you @agronholm.

**Comment by agronholm** [comment] 2019-07-29 12:08
What complicates matters here is that I am in the middle of a major refactoring effort that totally revamps the internals of APScheduler. As such, this would be a bad time for such a PR. But once I have managed to get the code base in a coherent state again I would welcome extra pairs of eyes to look over that code and re-evaluate the situation.

**Comment by b4stien** [comment] 2019-07-29 12:09
Cool, feel free to ping me if/when you want help on this matter 👍

**Comment by crhan** [comment] 2019-09-17 05:45
If you use a __str__ to present the `start_date` like `'2009-08-04T00:00:02+02:00'`. Then the `convert_to_datetime` function will return a __datetime__ object with a __tzinfo__ which is a __FixedOffset__ object.

The __FixedOffset__ object, which doesn't have the attribute `_utcoffset`, will report an error like below:

```python
tests/test_triggers.py:483: in test_before
    assert trigger.get_next_fire_time(None, now) == trigger.start_date
apscheduler/triggers/interval.py:66: in get_next_fire_time
    return self.timezone.normalize(next_fire_time)
../../.local/share/virtualenvs/playground-py3.7/lib/python3.7/site-packages/pytz/tzinfo.py:252: in normalize
    offset = dt.tzinfo._utcoffset
E   AttributeError: '_FixedOffset' object has no attribute '_utcoffset'
```

**Comment by agronholm** [comment] 2019-09-17 06:40
Ouch, sounds like a big oversight from me. Fortunately this is rather easy to work around. APScheduler 4.0 should not have issues like this.

**Comment by anoadragon453** [comment] 2020-06-10 00:33
I was able to convert a standard python dateutil timezone to a pytz-compatible one with the following:

```python
from apscheduler.util import timedelta_seconds

my_datetime = datetime.now()

# Get the timezone object's timezone offset in minutes
offset_minutes = timedelta_seconds(datetime.utcoffset(my_datetime)) / 60

# Create a pytz timezone object using the offset minutes
pytz_timezone = pytz.FixedOffset(offset_minutes)

# Replace the datetime's timezone object with the pytz one
start_time = start_time.replace(tzinfo=pytz_timezone)
```

Might not be the most efficient method, but it works :)

**Comment by agronholm** [comment] 2020-06-10 05:48
Can I ask what timezone this was? Non-pytz timezones tend to have rough edges around DST shifts.

**Comment by agronholm** [comment] 2020-06-10 06:30
Does your local timezone not have DST shifts at all?

**Comment by anoadragon453** [comment] 2020-06-10 09:31
Perhaps I'm just being naive in my implementation. The timezone is `Europe/London`.

**Comment by agronholm** [comment] 2020-06-10 10:47
The `Europe/London` timezone [does indeed have DST shifts](https://www.timeanddate.com/time/change/uk/london?year=2020). How this affects different triggers depends on the trigger. The cron trigger will work flat out wrong half of the year with this, as does the yet unpublished calendar interval trigger. The date and interval triggers will only display timestamps wrong in the job list.

**Comment by anoadragon453** [comment] 2020-06-10 11:47
Interesting, that's probably why my cron job was an hour off this morning :)

Is there a way to convert from standard python timezones to pytz ones while keeping DST information?

**Comment by anoadragon453** [comment] 2020-06-11 10:16
I'm thinking of just bypassing conversion by storing timezone database names and avoiding conversion to python's standard dateutil timezone altogether.

**Comment by agronholm** [comment] 2020-06-12 12:08
> I'm thinking of just bypassing conversion by storing timezone database names and avoiding conversion to python's standard dateutil timezone altogether.

Dateutil is a third party library, just as pytz is. Neither is considered any more "standard" than the other.

> Is there a way to convert from standard python timezones to pytz ones while keeping DST information?

I tried playing around with dateutil timezones. It should be noted that, unlike pytz which comes with its own copy of the Olsen database, dateutil relies on system-provided timezone data and thus will not work the same way on Windows.

The following snippet should go some way towards demonstrating why I stick with pytz and will not bother with dateutil:
```
>>> from datetime import datetime
>>> from dateutil.tz import gettz
>>> tz = gettz('Europe/Helsinki')
>>> tz.tzname(datetime.now())
'EEST'
>>> tz2.tzname(datetime(2020, 1, 1))
'EET'
```
As you can see, the official way to get the timezone name is not helpful.
```
>>> dt1 = datetime(2020, 3, 29, 2, 59, tzinfo=tz)
>>> dt1.isoformat()
'2020-03-29T02:59:00+02:00'
```
We get the correct UTC offset here. Let's try moving it 2 minutes forward which, taking the DST shift into account, should arrive at `2020-03-29T04:01:00+03:00`:
```
>>> dt2 = dt1 + timedelta(minutes=2)
>>> dt2
datetime.datetime(2020, 3, 29, 3, 1, tzinfo=tzfile('/usr/share/zoneinfo/Europe/Helsinki'))
```
Nonexistent time, but doesn't matter if we normalize, let's try to do that:
```
>>> datetime.fromtimestamp(dt2.timestamp(), tz).isoformat()
'2020-03-29T02:01:00+02:00'
```
Uh, what? How on Earth did it go _backwards_ when time was _added_ to the timestamp?
Let's try this another way – just add the minutes to the timestamp and make a new datetime from that:
```
>>> datetime.fromtimestamp(dt1.timestamp() + 2*60, tz).isoformat()
'2020-03-29T04:01:00+03:00'
```
_Now_ we get the correct answer. 

The biggest problem, however, is serialization. There is no way to reliably recreate instances of the `datetime.tzinfo` class without knowing where they came from unless `pickle` is used. Some library specific logic could be used, like checking what file a dateutil timezone points to. Additionally, local-bound timezones are problematic in that if the project is moved to another server, it will start using that server's local timezone, whatever it is. This may be what you want, or not. Either way this should be explicit.

Even relying on pickle might have been borderline acceptable on APScheduler 3.x, but 4.0+ will offer a variety of serializers so this approach will not work.

If you want a more comprehensive explanation of the issue, have a look at the [pytz documentation](http://pytz.sourceforge.net/).

**Comment by agronholm** [comment] 2020-09-29 21:12
I'm relaxing the tzinfo limitations in v4.0 so that at least named IANA timezones should be serializable whenever they can be accurately identified. Unfortunately it looks like this does not cover tzinfo objects from the dateutil library as they just point to file names.

**Comment by couling** [comment] 2021-04-08 12:36
This has been open quite a long time now.  I realise v4.0 refactor may still be ongoing.

Earlier in this thread @agronholm mentioned pitfalls of around DST unexpected behaviour.  There's one specific non-pytz timezone that I feel has been overlooked:  `datetime.timezone.utc`.  Frustratingly enough `pytz.UTC != datetime.timezone.utc`.  I bumped into that bug when I tried to:

    assert datetime.fromisoformat("2000-01-01 00:00:00+00:00").tzinfo == pytz.UTC

  This is a very exceptional case because unlike any other timezone there are no governments involved in it's administration, it has no DST and never will.  This justifiably could / should be an exception because the meaning of UTC is universal.

**Comment by agronholm** [comment] 2021-04-08 15:08
> This has been open quite a long time now. I realise v4.0 refactor may still be ongoing.

Yes, it is, and progress is sporadic since I am also working on several other projects. That said, the triggers part is more or less done, and it supports a far wider variety of tzinfo objects. Date-time arithmetic is done by converting the starting datetime to a timestamp, adding the desired number of seconds and then converting it back. That is the only way to get the semantics we want.

**Comment by mangelozzi** [comment] 2021-12-31 15:43
To risk pointing out the obvious, will APScheduler 4.0 work with `zoneinfo` (the replacement of pytz)?

For motivation why the communitiy is moving from pytz to zoneinfo see:
<https://docs.djangoproject.com/en/4.0/releases/4.0/#what-s-new-in-django-4-0>

PS `pytz` has been called [The fastest footgun in the west](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html)

**Comment by agronholm** [comment] 2022-01-01 12:34
It already does, in `master`.

**Comment by agronholm** [comment] 2022-08-17 20:57
v4.0.0a1 accepts a wider range of tzinfo objects. If you still have trouble, open a new issue against v4.0.0a1.

**Closed by agronholm** 2022-08-17 20:57 UTC
Labels: documentation
