### ISSUE TITLE
cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by LingjieLi** [agronholm/apscheduler#632] opened 2022-06-05 07:33 UTC
I have a flask app in a thread，when I start this flask app, i also start a aspscheduler(BackgroundScheduler) ，it report "cannot schedule new futures after interpreter shutdown", **authough flask app is still running**。

```
    controller = SlaveServerController(None)  # flask app，a thread
    controller.start()   # start thread，also start scheduler
    controller.controller_logger.info("create main thread, name = %s, daemon = %s", controller.getName(),
                                      controller.daemon)

    print("active thread: ", threading.active_count())
    print("thread message: ", threading.enumerate())

    def test_curl():
        print("test curl")
        print(os.system("curl http://www.baidu.com"))

    controller.add_job(test_curl, next_run_time=datetime.datetime.now() + datetime.timedelta(seconds=1))

    print("active thread: ", threading.active_count())
    print("thread message: ", threading.enumerate())
```

output:

```
active thread:  2
thread message:  [<_MainThread(MainThread, started 4698379776)>, <SlaveServerController(Thread-1, started 123145402093568)>]
 * Serving Flask app 'controller.flask_controller' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.31.236:9090/ (Press CTRL+C to quit)
/usr/local/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
active thread:  3
thread message:  [<_MainThread(MainThread, started 4698379776)>, <SlaveServerController(Thread-1, started 123145402093568)>, <Thread(APScheduler, started daemon 123145418883072)>]
Error submitting job "slave_server_usage.<locals>.test_curl (trigger: date[2022-06-05 15:02:43 CST], next run at: 2022-06-05 15:02:44 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by LingjieLi** [comment] 2022-06-05 07:52
I try use pdb ,it is not report this error. but i don't know why，and how modify my program.

**Comment by agronholm** [comment] 2022-06-05 17:07
Are you sure you read the issue template? You need to provide instructions to reproduce the problem. Are you also sure that you're running the latest APScheduler?

**Comment by stepacool** [comment] 2022-06-29 06:25
I have a lot of these after restarting my project. Running Flast-APScheduler of the latest version.

**Comment by agronholm** [comment] 2022-06-29 07:06
@stepacool again, not helping. Please provide instructions on how to reproduce the problem!

**Comment by agronholm** [comment] 2022-06-29 07:07
And without Flask-Apscheduler, because that is a third party project not supported here.

**Comment by agronholm** [comment] 2022-07-27 11:14
Repro instructions not provided in 4 weeks, closing.

**Closed by agronholm** 2022-07-27 11:14 UTC
