### ISSUE TITLE
Jobs stops being exeucted

### ISSUE THREAD

**Issue by Juanjoorrego** [agronholm/apscheduler#322] opened 2018-07-16 21:01 UTC
Hi there.

We have some jobs that trigger a script to run every 5 seconds (i.e. 720 GETS per hour). Unfortunately, some jobs never go from Started Execution to Executed, which means that other jobs that should be executed after it never execute. There is no error, or bug in the logs, for some reason it just doesn't stop at the time when it is supposed to (doesn't transition from Started Execution to Executed).

There is a Started time, but finished is not really populated until the job is done. We have tested entering a finished time (i.e. 1 hour from now - 3600), but it doesn't fix it. **Is there a reason for the job not going from Started Executed to Executed?** Secondly, **Why are multiple executions created for just one job?**

**Comment by agronholm** [comment] 2018-07-16 21:51
> Is there a reason for the job not going from Started Executed to Executed? 

What are these "Started Executed"?

> Why are multiple executions created for just one job?

That happens if the first run doesn't complete before the second one begins.

**Comment by Juanjoorrego** [comment] 2018-07-16 22:36
This is what I mean by the started executed:
Please also find the execution being added multiple times for the same job. Shouldn't it be just one?
![screen shot 2018-07-16 at 3 33 22 pm](https://user-images.githubusercontent.com/34254118/42787117-f0d720e6-890d-11e8-842a-20d39eee8420.png)

**Comment by agronholm** [comment] 2018-07-17 11:32
This seems to be Django-apscheduler. I am not the author of that project. Can you reproduce the problem using just plain APScheduler?

**Comment by agronholm** [comment] 2018-08-10 18:17
No answer – closing.

**Closed by agronholm** 2018-08-10 18:17 UTC
Labels: invalid
