### ISSUE TITLE
Multiple jobs with same job_id

### ISSUE THREAD

**Issue by e-remington-lee** [agronholm/apscheduler#388] opened 2019-08-12 23:30 UTC
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

## Expected Behavior
With a 'add_job(func=job, trigger='interval', seconds=5, replace_existing=True, id='blue43')' 1 job should be made and executed, and duplicates should be removed

## Current Behavior
multiple jobs are running at the same time:

works 2019-08-12 19:25:02.738609
works 2019-08-12 19:25:03.932659

jobs are occurring seconds after each other

## Steps to Reproduce

run this code, and then start and stop the python flask server.
def job():
    return print(datetime.now())
    
sch = BackgroundScheduler()

sch.add_job(func=job, trigger='interval', seconds=5, replace_existing=True, id='blue43')
sch.start()

atexit.register(lambda: sch.shutdown())

## Context (Environment)
python 3.7.2 using a python flask server

**Comment by agronholm** [comment] 2019-08-13 05:52
You need to provide a snippet I can run to reproduce the results. You talk about "the python flask server" but I have really no idea what you're talking about.

**Comment by e-remington-lee** [comment] 2019-08-13 13:02
Are you confused on what python and flask are or are you asking for a
requirements.txt file, I provided the code I ran in the description

**Comment by agronholm** [comment] 2019-08-13 13:10
The code cannot possibly work because there are no imports and the script exits right after starting the background scheduler. How are you running it?

**Comment by e-remington-lee** [comment] 2019-08-13 13:17
I see, I start  'from flask import Flask" and I create a flask server,
'from aspscheduler.schedulers.background import BackgroundScheduler' run
the code and at the bottom I have "if __main__ == '__main__': app.run()".
It's a a basic flask server with python, I can send you everything once I
get home from work.

**Comment by agronholm** [comment] 2019-08-13 13:19
Yes, please do. I want to make sure we're running the same code because it is a frequently occurring problem that bug reporters omit important parts of their code from their reports.

**Comment by agronholm** [comment] 2021-01-11 11:25
Closing due to no reply in 1.5 years.

**Closed by agronholm** 2021-01-11 11:25 UTC
