### ISSUE TITLE
Cron jobs executes more times than desired when using jitter

### ISSUE THREAD

**Issue by csanz91** [agronholm/apscheduler#291] opened 2018-03-07 21:55 UTC
When using the jitter option in a scheduled cron jobs, for example using the code from the documentation:
 
`# Run the `job_function` every sharp hour with an extra-delay picked randomly in a [-120,+120] seconds window.
sched.add_job(job_function, 'cron', hour='*', jitter=120)`

if the job is scheduled before the sharp hour then the job will be scheduled for the same hour again. For example:

- A Job is defined to be runned at sharp hours.

- Job is scheduled to run at 14:59:51

- Job runs at 14:59:51 but its scheduled to run at 15:00:02 again.
In this case we only want the job to run once at ~15:00:00.

Attached is a small piece of code to test this behaiviour: [test.zip](https://github.com/agronholm/apscheduler/files/1791019/test.zip)

**Comment by skhare-r7** [comment] 2018-10-25 18:19
I noticed the same behaviour, and it happens when it computes a negative jitter on a cron style job. Example:
- Job is cron every */10 seconds, with 5 second jitter
Without jitter, the job would execute at 
10, 20, 30, 40, 50, ..
With jitter, you'd expect the job to execute at
6, 18, 33, 43, 47, etc.(i.e. for every execution, advance or delay job by 0-5 seconds)

What happens is the job executes fine when it randoms a positive jitter, but a negative jitter causes it to re-schedule the job. So you'd have execution times like so
6 (original 10), 13 (rescheduled 10), 33, 43, 47, 49 (rescheduled 50), 52 (rescheduled 50)

**Comment by schizophrene** [comment] 2019-03-06 20:40
Same for me here, in `BlockingScheduler` (I didn't try why another one).

Any solution found ?

**Comment by matslindh** [comment] 2019-05-10 07:50
This is caused by the cron trigger not keeping track of when the actual last invocation should have taken place. We can probably work around this by tracking the last time it was _supposed_ to run (and not the last time it actually run), and then replace start_date at the [start of `get_next_fire_date`](https://github.com/agronholm/apscheduler/blob/18b50d9ee9ff14e816b557e34d7d3abc861d57e5/apscheduler/triggers/cron/__init__.py#L162) with the time it was supposed to run.

Something like:

    if self.previous_unjittered_time > start_date:
        start_date = self.previous_unjittered_time + timedelta(microsecond=1)

That change will add a bit more state to the cron trigger, but I'm not sure if we can work around that without any larger changes to track scheduled runs. I'll make a PR if this sounds like a decent strategy.

**Comment by agronholm** [comment] 2019-05-10 12:06
Sounds good. Remember to change the state version too.

**Comment by mkelc** [comment] 2019-06-18 14:31
Proposal: make the jitter having only a positive shift and remove the negative one.
All situations can be covered anyway:  e.g. minute=5, jitter=60 (~minute 4 to 6) is equivalent to minute = 4, jitter=120 (~minute 4 to 6) with only positive jitter. 
For me a nonnegative jitter sounds more logical anyway ...

**Comment by agronholm** [comment] 2019-06-19 10:50
I think that the proper fix for this is to separate the original scheduled time from the jitter and only use the original time for calculating the next fire time. I can do this in the next major release.

**Comment by matslindh** [comment] 2019-06-19 11:35
Great. I got caught up in a different project so I haven't had time to make a PR yet.

**Comment by rendorHaevyn** [comment] 2020-01-02 04:33
@matslindh Thanks Mat, any progress on this?  
I'm facing the same issue on jitter across several jobs, I have so I have to go jitter-free until implemented (not ideal, but, prefer a pure python scheduler to WinX).

**Comment by matslindh** [comment] 2020-01-02 23:16
Sorry, I ended up working around the issue in some other way and it got lost in time. Might have to look at it again soon.

**Comment by joseph8th** [comment] 2020-01-09 22:10
I'm having the same issue ... we hadn't really been using it, but our load is getting heavy and we started jitter-ing to break up the spikes. Would really appreciate a fix on this.

**Comment by agronholm** [comment] 2020-01-09 22:18
The short term solution would be to force jitter to always be positive, yes?

**Comment by agronholm** [comment] 2020-01-11 16:04
Please test the code in #416. I will merge it if it fixes the problem for you.

**Comment by matslindh** [comment] 2020-02-25 11:17
Code tested, works as expected outside of the jitter window now being halved (since it's only making the positive side of the window available for the jitter).

**Comment by agronholm** [comment] 2022-01-25 12:20
For the record, this has been addressed in master by ensuring that jitter always places the execution time after the last run time and before the next run time after that.

**Comment by agronholm** [comment] 2022-08-17 21:59
I'm closing this as done since v4.0.0a1 is out now.

**Closed by agronholm** 2022-08-17 21:59 UTC
