### ISSUE TITLE
Apscheduler initialization issue

### ISSUE THREAD

**Issue by gdmello** [agronholm/apscheduler#128] opened 2016-04-13 18:47 UTC
```
> python --version
Python 2.7.6
> pip -v
pip 1.5
```

Installed latest version via pip. Have a simple python program that begins as-

```python 
from apscheduler.schedulers import background
scheduler = background.BackgroundScheduler() 
```

when run from command line, the following stack trace is thrown -

```python
 $ python periodic_scheduler.py 
Traceback (most recent call last):
  File "periodic_scheduler.py", line 1, in <module>
    from apscheduler.schedulers import background
  File "/home/user/workspaces/.virtualenvs/aps/local/lib/python2.7/site-packages/apscheduler/__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public' 
```

Got the same error even by installing via setup.py.

**Comment by agronholm** [comment] 2016-04-13 19:56
Another duplicate of #123. This has been fixed and a new release will come out soon. Meanwhile please upgrade your setuptools.

**Closed by agronholm** 2016-04-13 19:56 UTC
Labels: duplicate
