### ISSUE TITLE
PytzUsageWarning when running on Windows 10 with tzlocal version 4.1

### ISSUE THREAD

**Issue by erismann** [agronholm/apscheduler#572] opened 2021-11-05 05:37 UTC
**Describe the bug**
Scheduling and executing jobs on Windows 10 triggers several PytzUsageWarnings when APScheduler is installed with tzlocal version 4.1. 
Downgrading tzlocal back to version 2.1, all the PytzUsageWarnings disappear.

Output of example running with tzlocal==4.1:

```
(test39-apscheduler) C:\test-apscheduler>test_combined.py
Schedule job with "interval" trigger
C:\pyenv\test39-apscheduler\lib\site-packages\apscheduler\util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
Schedule job with "cron" trigger
Schedule job with "date" trigger (date string)
Schedule job with "date" trigger (datetime)
C:\pyenv\test39-apscheduler\lib\site-packages\apscheduler\util.py:166: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tz.localize(datetime_, is_dst=None)
Start scheduler
C:\pyenv\test39-apscheduler\lib\site-packages\apscheduler\triggers\interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
C:\pyenv\test39-apscheduler\lib\site-packages\apscheduler\triggers\cron\__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
Press Ctrl+Break to exit
Tick - called by cron trigger! The time is: 2021-11-05 16:13:30.002081
Tick - called by interval trigger! The time is: 2021-11-05 16:13:35.333377
Tick - called by date trigger (datetime)! The time is: 2021-11-05 16:13:35.386150
Tick - called by cron trigger! The time is: 2021-11-05 16:13:40.000169
Tick - called by interval trigger! The time is: 2021-11-05 16:13:45.331971
C:\pyenv\test39-apscheduler\lib\site-packages\apscheduler\triggers\cron\__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
Tick - called by cron trigger! The time is: 2021-11-05 16:13:50.001817
Tick - called by interval trigger! The time is: 2021-11-05 16:13:55.331860
Tick - called by cron trigger! The time is: 2021-11-05 16:14:00.007463
Tick - called by interval trigger! The time is: 2021-11-05 16:14:05.332295
Tick - called by cron trigger! The time is: 2021-11-05 16:14:10.000612
```

Output of example running with tzlocal==2.1:

```
(test39-apscheduler) C:\test-apscheduler>test_combined.py
Schedule job with "interval" trigger
Schedule job with "cron" trigger
Schedule job with "date" trigger (date string)
Schedule job with "date" trigger (datetime)
Start scheduler
Press Ctrl+Break to exit
Tick - called by cron trigger! The time is: 2021-11-05 16:23:40.001474
Tick - called by interval trigger! The time is: 2021-11-05 16:23:40.163934
Tick - called by date trigger (datetime)! The time is: 2021-11-05 16:23:40.182566
Tick - called by cron trigger! The time is: 2021-11-05 16:23:50.000622
Tick - called by interval trigger! The time is: 2021-11-05 16:23:50.163640
```

**To Reproduce**
```
#!/usr/bin/env python
# -*- coding: <ascii> -*-

"""
Example to produce PytzUsageWarning for all 3 trigger types:
'interval', 'cron' and 'date'

Based on apscheduler/examples/schedulers/background.py example on Github 
"""

from datetime import datetime, timedelta
import time
import os

from apscheduler.schedulers.background import BackgroundScheduler


def tick(method):
    print('Tick - called by {}! The time is: {}'.format(method, datetime.now()))


if __name__ == '__main__':
    scheduler = BackgroundScheduler()

    print('Schedule job with "interval" trigger')
    scheduler.add_job(tick, 'interval', seconds=10, args=['interval trigger'])

    print('Schedule job with "cron" trigger')
    scheduler.add_job(tick, 'cron', second='*/10', args=['cron trigger'])

    print('Schedule job with "date" trigger (date string)')
    scheduler.add_job(tick, 'date', run_date='2021-11-06T14:44:00+11:00',
                      args=['date trigger (date string)'])

    print('Schedule job with "date" trigger (datetime)')
    alarm_time = datetime.now() + timedelta(seconds=10)
    scheduler.add_job(tick, 'date', run_date=alarm_time,
                      args=['date trigger (datetime)'])

    print('Start scheduler')
    scheduler.start()
    print('Press Ctrl+{0} to exit'.format('Break' if os.name == 'nt' else 'C'))

    try:
        # This is here to simulate application activity (which keeps the main thread alive).
        while True:
            time.sleep(2)
    except (KeyboardInterrupt, SystemExit):
        # Not strictly necessary if daemonic mode is enabled but should be done if possible
        scheduler.shutdown()
```

**Expected behavior**
No PytzUsageWarnings

**Additional context**
Python 3.9.7 on Windows 10
Created new virtual environment (venv)
Updated pip & setuptools and installed wheel
Installed APScheduler 3.8.1 with pip install APScheduler
```
Package               Version
--------------------- -----------
APScheduler           3.8.1
pip                   21.3.1
pytz                  2021.3
pytz-deprecation-shim 0.1.0.post0
setuptools            58.5.3
six                   1.16.0
tzdata                2021.5
tzlocal               4.1
wheel                 0.37.0
```

**Comment by agronholm** [comment] 2021-11-05 08:47
Duplicate of #569.

**Closed by agronholm** 2021-11-05 08:47 UTC
