### ISSUE TITLE
Breakage when starting the AsyncIOScheduler in 3.11

### ISSUE THREAD

**Issue by Lelor** [agronholm/apscheduler#994] opened 2024-11-25 17:47 UTC
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.11

### What happened?

After upgrading to the new release, the AsyncIOScheduler is breaking on start.
Running on python 3.11

### How can we reproduce the bug?

Executing this script raises the error:

```python
import asyncio

from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.schedulers.asyncio import AsyncIOScheduler


scheduler = AsyncIOScheduler(executors={"default": ThreadPoolExecutor(5)},
                             jobstores={"default": MemoryJobStore()})

scheduler.start()
```
Will throw the error
```
Traceback (most recent call last):
  File "/home/leorodr2/xpresso/onedevx_tests/banana.py", line 11, in <module>
    scheduler.start()
  File "/home/leorodr2/.local/share/virtualenvs/onedevx_tests-rjQ7VI62/lib/python3.11/site-packages/apscheduler/schedulers/asyncio.py", line 35, in start
    self._eventloop = asyncio.get_running_loop()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```

**Comment by agronholm** [comment] 2024-11-25 17:50
How did this ever work anyway? You're not running an async event loop here. Have you seen the provided [example](https://github.com/agronholm/apscheduler/blob/3.x/examples/schedulers/asyncio_.py)?

**Comment by agronholm** [comment] 2024-11-25 17:51
If you want to use all your jobs in a thread pool executor, why even bother with `AsyncIOScheduler`?

**Comment by Lelor** [comment] 2024-11-25 17:58
Thanks for the quick response!
I do have my reasons to run the async scheduler with worker threads that is not worth going into.
The provided example is a minimal set of calls that raises the error in 3.11 while still working in 3.10.4.

I was counting on APScheduler to create the loop there, but if this is a known breaking change I'm happy to fix it on my end.

**Comment by agronholm** [comment] 2024-11-25 18:11
> I do have my reasons to run the async scheduler with worker threads that are not worth going into.

On the contrary, I'd love to hear them because the only reason for the existence of `AsyncIOScheduler` is to run coroutine based jobs.

> I was counting on APScheduler to create the loop there, but if this is a known breaking change I'm happy to fix it on my end.

The weird thing is, I have no clue how this could work at all, as nothing is even starting the event loop. The script just exits after `start()`.

**Comment by agronholm** [comment] 2024-11-25 18:29
This has been working "by accident" for you so far. The only reason I've used `get_event_loop()` is because the newer `get_running_loop()` didn't exist back when I wrote `AsyncIOScheduler`. `get_event_loop()` has been [deprecated](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) in Python 3.12 and should not be used under any circumstances.

I don't want to revert this change, as it does away with the use of a dangerous function (people have inadvertently created multiple event loops with this and then wonder why the scheduler doesn't do anything). It should be easy for you to adapt though.

**Comment by geovalexis** [comment] 2024-11-25 18:36
This is also breaking some of my code in production. I've checked the example provided and see no difference with what I am doing. The only reason of using AsyncIOScheduler() API over the regular scheduler is to handle asynchronous functions in FastAPI.

Should we avoid using  `scheduler.start()` then? Sorry, I don't get to understand what's wrong with the piece of code @Lelor  provided.

**Comment by agronholm** [comment] 2024-11-25 18:39
> Should we avoid using `scheduler.start()` then? Sorry, I don't get to understand what's wrong with the piece of code @Lelor provided.

It should either be run in an existing event loop (preferred), or given an event loop as an argument at start. May I see how you're starting your scheduler?

**Comment by Lelor** [comment] 2024-11-25 18:57
> This has been working "by accident" for you so far. The only reason I've used `get_event_loop()` is because the newer `get_running_loop()` didn't exist back when I wrote `AsyncIOScheduler`. `get_event_loop()` has been [deprecated](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop) in Python 3.12 and should not be used under any circumstances.
> 
> I don't want to revert this change, as it does away with the use of a dangerous function (people have inadvertently created multiple event loops with this and then wonder why the scheduler doesn't do anything). It should be easy for you to adapt though.

Understood, It's fair to move away from soon-to-be deprecated code.
I'll fix this on my end.
Thanks!

**Comment by geovalexis** [comment] 2024-11-25 18:59
Fortunately there was a test that caught this error. However, I wouldn't expect a minor version upgrade to break anything. I have the version of the packages pinned to only minor and patches for this reason. 

Here is how I am currently starting APScheduler process:
```python
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from apscheduler.jobstores.memory import MemoryJobStore
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.schedulers.base import BaseScheduler

scheduler: BaseScheduler = AsyncIOScheduler(jobstores={"default": MemoryJobStore()})
queue_process_job_id = "process_queue_scheduler"

logger = logging.getLogger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    ## Setup logging
    logging_format = "%(asctime)s file %(filename)s: line %(lineno)s function  %(funcName)s() message %(message)s"
    logging.basicConfig(format=logging_format, level=logging.INFO)
    logger.info("Starting up application")
    ## Setup the scheduler
    scheduler.start()
    yield
    logger.info("Shutting down application")
    scheduler.shutdown()

app = FastAPI(
    title="My API",
    version="1.0.0",
    description="My app description",
    lifespan=lifespan,
)

# Use `app` to include routers, middlewares, etc...
```

I don't remember exactly why I put it into the FastAPI's lifespan but it makes sense given that I use APScheduler as a background process.

**Comment by agronholm** [comment] 2024-11-25 19:31
> Fortunately there was a test that caught this error. However, I wouldn't expect a minor version upgrade to break anything. I have the version of the packages pinned to only minor and patches for this reason.
> 
> Here is how I am currently starting APScheduler process:
> 
> ```python
> import logging
> from contextlib import asynccontextmanager
> 
> from fastapi import FastAPI
> from apscheduler.jobstores.memory import MemoryJobStore
> from apscheduler.schedulers.asyncio import AsyncIOScheduler
> from apscheduler.schedulers.base import BaseScheduler
> 
> scheduler: BaseScheduler = AsyncIOScheduler(jobstores={"default": MemoryJobStore()})
> 
> logger = logging.getLogger(__name__)
> 
> @asynccontextmanager
> async def lifespan(app: FastAPI):
>     ## Setup logging
>     logging_format = "%(asctime)s file %(filename)s: line %(lineno)s function  %(funcName)s() message %(message)s"
>     logging.basicConfig(format=logging_format, level=logging.INFO)
>     logger.info("Starting up application")
>     ## Setup the scheduler
>     scheduler.start()
>     yield
>     logger.info("Shutting down application")
>     scheduler.shutdown()
> 
> app = FastAPI(
>     title="My API",
>     version="1.0.0",
>     description="My app description",
>     lifespan=lifespan,
> )
> 
> # Use `app` to include routers, middlewares, etc...
> ```
> 
> I don't remember exactly why I put it into the FastAPI's lifespan but it makes sense given that I use APScheduler as a background process.

Hang on...this should work, as you're starting it with an active event loop. Can you give me further details on what is going wrong here?

**Comment by geovalexis** [comment] 2024-11-26 09:21
@agronholm you are right, that piece of code is working fine. What it is failing though is the test. Looks like I need add additional setup to pytest to make it work. Sorry for the confusion!

**Comment by geovalexis** [comment] 2024-11-26 10:07
For future reference, this is what I had to add in my tests to fix this issue:

```python
import asyncio
import pytest

from myapp.scheduler import scheduler

@pytest.fixture(scope="module")
def event_loop():
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()

@pytest.mark.usefixtures("event_loop")
@pytest.fixture(scope="module", autouse=True)
async def scheduler_lifespan():
    scheduler.start()
    yield
    scheduler.shutdown()
```

**Comment by agronholm** [comment] 2024-11-26 10:09
> For future reference, this is what I had to add in my tests to fix this issue:
> 
> ```python
> import asyncio
> import pytest
> 
> from myapp.scheduler import scheduler
> 
> @pytest.fixture(scope="module")
> def event_loop():
>     loop = asyncio.get_event_loop_policy().new_event_loop()
>     yield loop
>     loop.close()
> 
> @pytest.mark.usefixtures("event_loop")
> @pytest.fixture(scope="module", autouse=True)
> async def scheduler_lifespan():
>     scheduler.start()
>     yield
>     scheduler.shutdown()
> ```

Why the `usefixtures`? And do you intend to use the same scheduler lifespan across all tests in a module? This doesn't make a ton of sense to me.

**Comment by agronholm** [comment] 2024-11-26 10:13
If you're using `pytest-asyncio` to provide async testing capabilities, then it comes with its own event loop fixture, so you don't need to provide one yourself.

**Comment by geovalexis** [comment] 2024-11-26 10:18
Yess, I am using that same library and that's what I thought too but turns out not to be working for me. And yes, I am using the same scheduler lifespan across the test module given that some tests have crossed dependencies between each other.

**Comment by agronholm** [comment] 2024-11-26 10:21
Are you sure you configured the event loop scope to be on the module level? [Here](https://pytest-asyncio.readthedocs.io/en/latest/reference/configuration.html#asyncio-default-fixture-loop-scope) are the docs on that.

**Comment by geovalexis** [comment] 2024-11-26 10:35
Yeah, I spent a bit of time figuring it that out. I first tried to use this decorator `@pytest.mark.asyncio(loop_scope="module")` but none of that worked.

**Comment by agronholm** [comment] 2024-11-26 17:37
Ok, sounds like it works fine when used correctly, so I'm going to close this.

**Closed by agronholm** 2024-11-26 17:37 UTC
Labels: bug

**Comment by aliencaocao** [comment] 2024-11-29 03:04
Have the same issue, and I have to say, such a sudden change is very unexpected. No matter if it was intended or not, it was clearing WORKING as intended for me prior to 3.11.

My use case is using a scheduler to run a async function, together with a telegram bot, which itself uses aiohttp. So 2 async libs involved.

If I follow the example you give:

```    async def start_scheduler():
        scheduler.start()
      asyncio.run(start_scheduler())
```

Then I will have python-telegram-bot library's `application.run_polling()` error: `RuntimeError: There is no current event loop in thread 'MainThread'.`

Whatever it is that allow it to work in version 3.10.4, how do I correctly migrate it?

**Comment by agronholm** [comment] 2024-11-29 09:09
> Have the same issue, and I have to say, such a sudden change is very unexpected. No matter if it was intended or not, it was clearing WORKING as intended for me prior to 3.11.
> 
> My use case is using a scheduler to run a async function, together with a telegram bot, which itself uses aiohttp. So 2 async libs involved.
> 
> If I follow the example you give:
> 
> ```
> async def start_scheduler():
>         scheduler.start()
>       asyncio.run(start_scheduler())
> ```
> 
> Then I will have python-telegram-bot library's `application.run_polling()` error: `RuntimeError: There is no current event loop in thread 'MainThread'.`
> 
> Whatever it is that allow it to work in version 3.10.4, how do I correctly migrate it?

Looking at the quickstart for `python-telegram-bot`, this seems to be how it's launched:
```py
import asyncio
import telegram


async def main():
    bot = telegram.Bot("TOKEN")
    async with bot:
        print(await bot.get_me())


if __name__ == '__main__':
    asyncio.run(main())
```
The scheduler would be started before the bot, I think. How are you using it?

**Comment by aliencaocao** [comment] 2024-11-29 09:14
No this is not how it's launched. See https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---Your-first-Bot

`application.run_polling()application.run_polling()`

I think you were looking at a different library.

**Comment by agronholm** [comment] 2024-11-29 09:20
No, we were definitely looking at the same library. Curiously that wiki page uses a vastly different syntax for launching it. No matter, you can still launch the scheduler in the start handler. But how are you doing it right now?

**Comment by aliencaocao** [comment] 2024-11-29 09:21
```python
    async def start_scheduler():
        scheduler.start()

    asyncio.run(start_scheduler())

    application.run_polling()
    ```

**Comment by agronholm** [comment] 2024-11-29 09:24
That's now how it's done. `asyncio.run()` creates a new event loop and then shuts it down when done. Then `application.run_polling()` will start a new one. So my recommendation is that you switch to the [newer syntax](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API), as it will also allow APScheduler 4 to work with it. But if you want to stick with the older syntax, start the scheduler in a start handler, as mention on the page you linked to.

**Comment by aliencaocao** [comment] 2024-11-29 09:27
the newer syntax is actually the simplied version of the library, the one I am using is not "old" but a more low level access to functions.

I'm not sure which is the "start handler" you refer to, if you mean the "start_handler = CommandHandler('start', start)", that wont work because it only triggers if user send a start to the bot.

**Comment by agronholm** [comment] 2024-11-29 09:30
How about [post_init()](https://docs.python-telegram-bot.org/en/stable/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.post_init) then?

**Comment by aliencaocao** [comment] 2024-11-29 09:38
I see. This does work. Thank you for your help

**Comment by agronholm** [comment] 2024-11-30 11:32
The `Application` class returned by `ApplicationBuilder` also supports use as an async context manager:
```py
async def main():
    application = ApplicationBuilder().token('TOKEN').build()
    start_handler = CommandHandler('start', start)
    application.add_handler(start_handler)

    scheduler = AsyncIOScheduler()
    scheduler.add_job(...)
    scheduler.start()

    async with application:
        await asyncio.sleep(float("inf"))
```
